--- #YAML:1.0
name:               Image-Imlib2-Thumbnail
version:            0.40
abstract:           Generate a set of thumbnails of an image
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    Image::Imlib2:        2.00
    MIME::Types:          0
    Path::Class:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
